# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pyRevit blog
email: eirannejad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IronPython scripts for Autodesk Revit
baseurl: "/pyRevit" # the subpath of your site, e.g. /blog
url: "http://eirannejad.github.io" # the base hostname & protocol for your site
twitter:
  username: eirannejad
github_username:  eirannejad

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins_dir:
  - jekyll-seo-tag
